name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Update README with current year
        uses: actions/github-script@v7
        with:
          script: |
            const currentYear = new Date().getFullYear()
            document.getElementById('current_year').textContent = currentYear
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

